### ISSUE TITLE
thanks for putting this online!

### ISSUE THREAD

**Issue by karinlag** [cdeanj/nextflow-tychus#8]
Couldn't figure out a different way of contacting you, so just thought I'd do it this way.

I've been figuring out nextflow for the last couple of weeks. I'm doing a lot of the same things that you are. Seeing this code has helped me immensely in figuring out how to put my stuff together, so I thought I'd just say thanks :smile:

**Comment by cdeanj** [comment]
Oh, wow. That's great!

Sorry for the late reply. I never check this email. I should change it to
my school one.

I'm glad it was helpful to you.

Best,
Chris
