### ISSUE TITLE
docker pull error for assembly module

### ISSUE THREAD

**Issue by ap1438** [cdeanj/nextflow-tychus#9]
$docker pull abdolab/tychus-assembly
Using default tag: latest
latest: Pulling from abdolab/tychus-assembly
b3e1c725a85f: Already exists 
4daad8bdde31: Already exists 
63fe8c0068a8: Already exists 
4a70713c436f: Already exists 
bd842a2105a8: Already exists 
f7b83705331b: Pull complete 
040e9fb722e8: Downloading [=========================================>         ]  168.6MB/205.2MB
5ea286e32f2a: Download complete 
4f5e4e724131: Download complete 
43419d7ef3e7: Downloading [===========>                                       ]  156.9MB/669.7MB
3e84488ddcb2: Download complete 
87a3d52abacf: Downloading 
e135eb35057b: Waiting 
48ff4a2c0ec3: Waiting 
67007af7d25f: Waiting 
7d9d56220ac8: Waiting 
4dc87af1ccf3: Waiting 
4b641b8e6cbf: Waiting 
846d20600e27: Waiting 
unauthorized: authentication required

I am getting this error while trying to pull the assembly module from docker
Please let me know how to resolve this issue
 I am using the latest docker version 20.10.12

**Comment by kp54321** [comment]
I am also facing the same issue.

**Comment by ap1438** [comment]
Please move to new link
